import { rolexBottomDescImg } from "../../common/assets/images/imageFile";
import { ColorScheme } from "../../config/colorPalette";

export const ReadShopComponentStyles = (colors: ColorScheme) => ({
  mainContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    flexDirection: "column",
    minHeight: "100vh",
  },
  heroImage: {
    width: "100%",
    height: { xs: 250, sm: 350, md: 450, lg: 500 },
    mb: { xs: 2, sm: 3 },
  },
  heroImageContent: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  sectionContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: { xs: "flex-start", md: "center" },
    width: { xs: "95%", sm: "90%", md: "80%" },
    mb: { xs: 3, sm: 4 },
  },
  title: {
    width: { xs: "100%", md: "60%" },
    textAlign: { xs: "left", md: "justify" },
    mb: 2,
    fontSize: { xs: "1.75rem", sm: "2.25rem", md: "3rem" },
    fontFamily: "miller-light",
  },
  subtitle: {
    width: { xs: "100%", md: "90%" },
    textAlign: "left",
    mb: 2,
    color: colors.textGrey,
    fontFamily: "miller-light",
  },
  span: { fontWeight: "bold", marginLeft: 1 },
  text: {
    width: { xs: "100%", md: "90%" },
    textAlign: "left",
    color: colors.textGrey,
    fontSize: ".8rem",
    fontFamily: "miller-light",
  },
  imageSection: {
    display: "flex",
    flexDirection: { xs: "column", sm: "row" },
    gap: { xs: 1, sm: 2 },
    justifyContent: "center",
    width: "100%",
    mb: { xs: 3, sm: 4 },
  },
  imageBox: {
    width: { xs: "95%", sm: "45%", md: "40%" },
    height: { xs: 250, sm: 350, md: 450 },
    overflow: "hidden",
    alignSelf: "center",
  },
  watchDescriptionSection: {
    width: { xs: "95%", sm: "90%", md: "80%" },
    textAlign: "left",
    mb: { xs: 3, sm: 4 },
  },
  watchTitle: {
    mb: 2,
    fontSize: { xs: "1.25rem", sm: "1.5rem", md: "1.75rem" },
    textAlign: "center",
    fontFamily: "miller-light",
  },
  watchSubTitle: {
    mb: 2,
    color: colors.textGrey,
    fontSize: ".8rem",
    fontFamily: "miller-light",
  },
  containerStyle: { mt: { xs: 2, sm: 3, md: 4 }, mb: { xs: 2, sm: 3, md: 4 }, px: { xs: 1, sm: 2, md: 3 } },
  boxStyle: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    gap: { xs: 2, md: 4 },
    justifyContent: "center",
    alignItems: "center",
  },
  boxContentContainer: { width: { xs: "100%", md: "40%" } },
  boxContentImg: {
    width: "100%",
    borderRadius: 1,
    backgroundColor: "#025a5a",
    objectFit: "contain",
  },
  boxContentHeading: { display: "block", mt: 1, fontSize: "0.8rem", fontFamily: "miller-light" },
  subContainerStyles: {
    width: { xs: "100%", md: "40%" },
    justifyContent: "center",
    alignItems: { xs: "flex-start", md: "center" },
    display: "flex",
    flexDirection: "column",
  },
  subContainerSubText: { fontSize: "0.8rem", fontFamily: "miller-light" },

  subContainerHeading: { fontWeight: "normal", fontSize: { xs: "1.75rem", sm: "2rem", md: "2.5rem" }, fontFamily: "miller-light" },

  bottomBanner: {
    minWidth: 1260,
  },
  bottomBannerImage: {
    position: "relative",
    height: { xs: 250, sm: 300, md: 350 },
    backgroundImage: `url(${rolexBottomDescImg})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    color: "white",
    textAlign: "center",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.4)",
      zIndex: 1,
    },
    width: "100%",
    mt: { xs: 2, sm: 3 },
  },
  bottomBannerContent: {
    zIndex: 2,
    px: { xs: 2, sm: 3, md: 4 },
    maxWidth: "100%",
  },
  bottomBannerContentHeading: {
    display: "block",
    fontSize: { xs: "12px", sm: "14px" },
    letterSpacing: 2,
    mb: { xs: 1, sm: 2 },
  },
  bottomBannerTitle: {
    fontFamily: "miller-light",
    fontWeight: 400,
    mb: { xs: 2, sm: 3, md: 4 },
    fontSize: { xs: "1.5rem", sm: "2rem", md: "2.5rem" },
    px: { xs: 1, sm: 2, md: 4 },
  },
  bottomBannerButton: {
    borderColor: "white",
    color: "white",
    borderWidth: "1px",
    borderRadius: 0,
    px: { xs: 3, sm: 4 },
    py: { xs: 1, sm: 1.5 },
    "&:hover": {
      borderColor: "white",
      backgroundColor: "rgba(255,255,255,0.1)",
    },
  },
});
