export const styles = {
  container: { py: 5 },
  title: { textAlign: "center", mb: 5, fontFamily: "serif", fontWeight: 400 },
  productImage: { height: 140, objectFit: "contain" },
  newBadge: { position: "absolute", top: 10, left: 10, bgcolor: "white", px: 1, py: 0.5, borderRadius: "4px", fontSize: "0.75rem" },
  brandText: { fontWeight: 600, mb: 0.5 },
  productInfo: { mb: 2 },
  quantitySelect: { "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0, 0, 0, 0.23)" } },
  priceText: { mt: 2, fontWeight: 400 },
  actionButtons: { mt: 2, display: "flex", gap: 2 },
  actionButton: { color: "text.secondary", textTransform: "none", fontWeight: 400 },
  orderSummary: { border: "1px solid rgba(0, 0, 0, 0.12)", p: 3 },
  orderSummaryTitle: { mb: 3, fontWeight: 500 },
  summaryRow: { mb: 2, display: "flex", justifyContent: "space-between" },
  totalRow: { mb: 4, display: "flex", justifyContent: "space-between", fontWeight: 500 },
  checkoutButton: {
    py: 1.5,
    bgcolor: "#0A2E1A",
    "&:hover": { bgcolor: "#0A2E1A", opacity: 0.9 },
    textTransform: "none",
    fontWeight: 500,
  },
  continueShoppingLink: {
    color: "#0A2E1A",
    fontWeight: 500,
    textDecoration: "underline",
    "&:hover": { color: "#0A2E1A", opacity: 0.8 },
  },
};
